# Generated by Django 3.2.25 on 2024-07-02 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('template_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('page_id', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=255)),
                ('app_id', models.CharField(max_length=100)),
                ('app_secret', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('az', 'Azerbaijani'), ('zh', 'Chinese'), ('cs', 'Czech'), ('nl', 'Dutch'), ('eo', 'Esperanto'), ('fi', 'Finnish'), ('fr', 'French'), ('de', 'German'), ('el', 'Greek'), ('hi', 'Hindi'), ('hu', 'Hungarian'), ('id', 'Indonesian'), ('ga', 'Irish'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('fa', 'Persian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('sk', 'Slovak'), ('es', 'Spanish'), ('sv', 'Swedish'), ('tr', 'Turkish'), ('uk', 'Ukranian'), ('vi', 'Vietnamese')], default='en', max_length=10)),
                ('templates', models.ManyToManyField(to='template_manager.Template')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts_photo/')),
                ('description', models.TextField()),
                ('recipe_name', models.CharField(max_length=100)),
                ('publication_time', models.DateTimeField(blank=True, null=True)),
                ('publish_now', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PostFacebookPageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('recipe_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_page_templates/')),
                ('is_published', models.BooleanField(default=False)),
                ('failure_message', models.TextField(default='The post has not been published yet!')),
                ('facebook_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.facebookpage')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='template_manager.template')),
            ],
            options={
                'unique_together': {('post', 'facebook_page')},
            },
        ),
        migrations.CreateModel(
            name='PostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(auto_now_add=True)),
                ('post_page_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.postfacebookpagetemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='facebook_pages',
            field=models.ManyToManyField(through='posts.PostFacebookPageTemplate', to='posts.FacebookPage'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
