# Generated by Django 5.0.6 on 2024-06-16 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('template_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('page_id', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=255)),
                ('templates', models.ManyToManyField(to='template_manager.template')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts_photo/')),
                ('description', models.TextField()),
                ('recipe_name', models.CharField(max_length=100)),
                ('publication_time', models.DateTimeField(blank=True, null=True)),
                ('recurring_schedule', models.CharField(blank=True, max_length=100, null=True)),
                ('publish_now', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostFacebookPageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.facebookpage')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='template_manager.template')),
            ],
            options={
                'unique_together': {('post', 'facebook_page')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='facebook_pages',
            field=models.ManyToManyField(through='posts.PostFacebookPageTemplate', to='posts.facebookpage'),
        ),
        migrations.CreateModel(
            name='PostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(auto_now_add=True)),
                ('post_page_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.postfacebookpagetemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
