# Generated by Django 5.0.6 on 2024-07-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_comment_postfacebookpagetemplate_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_time', models.DateTimeField(blank=True, null=True)),
                ('interval_hours', models.IntegerField()),
                ('interval_minutes', models.IntegerField()),
                ('publish_now', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('number_succes_logs', models.IntegerField(default=0)),
                ('facebook_pages', models.ManyToManyField(related_name='background_tasks', to='posts.facebookpage')),
                ('selected_logs', models.ManyToManyField(related_name='background_tasks', to='posts.postlog')),
            ],
        ),
    ]
