# Generated by Django 5.0.6 on 2024-06-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_facebookpage_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfacebookpagetemplate',
            name='failure_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postfacebookpagetemplate',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facebookpage',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('az', 'Azerbaijani'), ('zh', 'Chinese'), ('cs', 'Czech'), ('nl', 'Dutch'), ('eo', 'Esperanto'), ('fi', 'Finnish'), ('fr', 'French'), ('de', 'German'), ('el', 'Greek'), ('hi', 'Hindi'), ('hu', 'Hungarian'), ('id', 'Indonesian'), ('ga', 'Irish'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('fa', 'Persian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('sk', 'Slovak'), ('es', 'Spanish'), ('sv', 'Swedish'), ('tr', 'Turkish'), ('uk', 'Ukranian'), ('vi', 'Vietnamese')], default='en', max_length=10),
        ),
    ]
