# Generated by Django 5.0.6 on 2024-06-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_postfacebookpagetemplate_failure_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfacebookpagetemplate',
            name='failure_message',
            field=models.TextField(default='The post has not been published yet!'),
        ),
    ]
