# Generated by Django 3.2.25 on 2024-07-02 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('font_type', models.CharField(choices=[('DejaVu Sans', 'DejaVu Sans')], max_length=100)),
                ('text_color', models.CharField(max_length=7)),
                ('text_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)])),
                ('stroke_thickness', models.IntegerField(default=0, help_text='Test', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('stroke_color', models.CharField(blank=True, max_length=7, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='templates_backgrounds/')),
                ('text_position', models.CharField(choices=[('top_left', 'Top Left'), ('top_center', 'Top Center'), ('top_right', 'Top Right'), ('middle_left', 'Middle Left'), ('middle_center', 'Middle Center'), ('middle_right', 'Middle Right'), ('bottom_left', 'Bottom Left'), ('bottom_center', 'Bottom Center'), ('bottom_right', 'Bottom Right')], max_length=30)),
            ],
        ),
    ]
