# Generated by Django 5.0.6 on 2024-07-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_manager', '0002_alter_template_font_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='background_position',
            field=models.CharField(blank=True, choices=[('top', 'Top'), ('bottom', 'Bottom')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='bounding_box',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='font_type',
            field=models.CharField(choices=[('Fustat-Bold', 'Fustat-Bold')], max_length=100),
        ),
    ]
