# Generated by Django 5.0.6 on 2024-06-17 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_manager', '0002_alter_template_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='stroke',
        ),
        migrations.AlterField(
            model_name='template',
            name='stroke_thickness',
            field=models.IntegerField(default=0, help_text='Test', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
