# Generated by Django 5.0.6 on 2024-07-10 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template_manager', '0003_template_background_position_template_bounding_box_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='text_position',
        ),
    ]
