# Generated by Django 5.0.6 on 2024-07-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_manager', '0005_alter_template_font_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='font_type',
            field=models.CharField(max_length=255),
        ),
    ]
